apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: testeapp
  namespace: flux-system
spec:
  interval: 1m
  path: "./apps/testeapp"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true