apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
      version: 2.5.1
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  storageNamespace: keda
  targetNamespace: keda