apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations: {}
  name: redis-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: redis-operator
      sourceRef:
        kind: HelmRepository
        name: ot-helm
      version: 0.9.0
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: redis-operator
  storageNamespace: redis-operator
  targetNamespace: redis-operator